language: c
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
# install: pip install -r requirements.txt --use-mirrors
# command to run tests

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libzmq libzmq-dev
 
script: make check && make all && make tests
